-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'e0e5a5ecd0af99de' HASH 'dc68c0d2530bf5d972b1dcb696454b3ecfb2d1479b76d9f810dcc55fe4c0d7be' ADMIN;         
DROP TABLE IF EXISTS "PUBLIC"."TODO" CASCADE; 
DROP TABLE IF EXISTS "PUBLIC"."TOKEN_ENTITY" CASCADE;         
DROP TABLE IF EXISTS "PUBLIC"."USER_ENTITY" CASCADE;          
CREATE MEMORY TABLE "PUBLIC"."TODO"(
    "DONE" BOOLEAN NOT NULL,
    "EXECUTION_TIME" TIME(6),
    "LAST_EXECUTION_DATE" DATE,
    "ID" CHARACTER VARYING(255) NOT NULL,
    "TARGET_NAME" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "USER_ID" CHARACTER VARYING(255),
    "STATE" ENUM('COMPLETED', 'ERROR', 'IN_PROGRESS', 'PENDING')
);    
ALTER TABLE "PUBLIC"."TODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TODO;    
CREATE MEMORY TABLE "PUBLIC"."TOKEN_ENTITY"(
    "EXPIRES_IN" INTEGER,
    "REFRESH_TOKEN_EXPIRES_IN" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "USER_ID" UUID NOT NULL,
    "ACCESS_TOKEN" CHARACTER VARYING(255),
    "REFRESH_TOKEN" CHARACTER VARYING(255),
    "TOKEN_TYPE" CHARACTER VARYING(255)
);          
ALTER TABLE "PUBLIC"."TOKEN_ENTITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("USER_ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_ENTITY;            
CREATE MEMORY TABLE "PUBLIC"."USER_ENTITY"(
    "ID" UUID NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "KAKAOAUTHTOKEN" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE "PUBLIC"."USER_ENTITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_ENTITY;             
ALTER TABLE "PUBLIC"."USER_ENTITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" UNIQUE("EMAIL");   
